# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Admin\Desktop/untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(316, 241)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(200, 70, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnGenereit = QtWidgets.QPushButton(self.centralwidget)
        self.btnGenereit.setGeometry(QtCore.QRect(130, 140, 61, 41))
        self.btnGenereit.setStyleSheet("background-color: rgb(60, 105, 255);\n"
"color: rgb(88, 255, 11);\n"
"border: 3px solid darkgreen;\n"
"border-radius: 5px;")
        self.btnGenereit.setObjectName("btnGenereit")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(10, 50, 61, 31))
        self.checkBox.setStyleSheet("background-color: rgb(170, 85, 127);")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 80, 61, 31))
        self.checkBox_2.setStyleSheet("background-color: rgb(255, 0, 127);")
        self.checkBox_2.setObjectName("checkBox_2")
        self.tilt = QtWidgets.QLabel(self.centralwidget)
        self.tilt.setGeometry(QtCore.QRect(90, -10, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.tilt.setFont(font)
        self.tilt.setMouseTracking(False)
        self.tilt.setStyleSheet("color: rgb(255, 255, 0);")
        self.tilt.setObjectName("tilt")
        self.tiltuit = QtWidgets.QLabel(self.centralwidget)
        self.tiltuit.setGeometry(QtCore.QRect(130, 50, 51, 31))
        font = QtGui.QFont()
        font.setUnderline(True)
        font.setStrikeOut(False)
        self.tiltuit.setFont(font)
        self.tiltuit.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"color: rgb(0, 67, 0);\n"
"border: 3px solid gold;\n"
"border-radius: 5px;")
        self.tiltuit.setObjectName("tiltuit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 316, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnGenereit.setText(_translate("MainWindow", "Згенерувати"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_2.setText(_translate("MainWindow", "CheckBox"))
        self.tilt.setText(_translate("MainWindow", "Генератор паролів"))
        self.tiltuit.setText(_translate("MainWindow", "Результат"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
